g = time_graph(Node, 1)
time(g)
a = Node("a")
b = Node("b")
e1 = Edge(a, b)
add_node!(g, a)
add_node!(g, b)
add_edge!(g, e1)
out_neighbors(g, a)
has_node(g, a)

g2 = time_graph(Int, 2)
e2 = Edge(1,2)
e3 = Edge(2,3)
add_edge!(g2, e2)
add_edge!(g2, e3)
eg = evolving_graph(Int, Int)
add_graph!(eg, g2)
